### ISSUE TITLE
layers "readOnly: true"

### ISSUE THREAD

**Issue by luvagarwal** [fabianbormann/osm-map#4]
Hey, in https://github.com/fabianbormann/osm-map/blob/master/osm-map.html#L85 the value of `layers` property is set to read only. This disables resetting `this.layers` to `[]` in https://github.com/fabianbormann/osm-map/blob/master/osm-map.html#L166. This causes repetition of elements in layers array every time `updateLayers` function is called.

Possible solutions:
1. Change `this.layers = []` to `this.layers.length = 0`. It looks like read only variables cannot be resetted but updated.
2. Remove `readOnly: true`?
3. Change `this.layers = []` to `this._setLayers([])`

**Comment by fabianbormann** [comment]
closes #7bfa3b4

**Comment by fabianbormann** [comment]
closed by 7bfa3b4
